#!/bin/bash

set -eu

BASE=$(pwd)

PATH_TO_SOURCES=/home/user
PATH_TO_BINARIES=$BASE/binaries
PATH_TO_PROFILES=$BASE/profiles
PATH_TO_RESULTS=$BASE/results
PATH_TO_LOGS=$BASE/logs
PATH_TO_BAG=$BASE/RESULTS
PATH_TO_EXT=$BASE/EXISTING

PATH_TO_CREATE_LLVM_PROF=/home/user/autofdo/build

PATH_TO_BENCHMARK_LLVM_BUILD=$BASE/benchmark_llvm_build
PATH_TO_LLVM_BUILDS=$BASE/llvm_builds
PATH_TO_AUTOFDO_LLVM_BUILDS=$PATH_TO_LLVM_BUILDS/autofdo

COMMON_CMAKE_FLAGS=(
    "-DLLVM_OPTIMIZED_TABLEGEN=On"
    "-DCMAKE_BUILD_TYPE=RelWithDebInfo"
    "-DENABLE_LINKER_BUILD_ID=On"
    "-DLLVM_TARGETS_TO_BUILD=X86"
    "-DLLVM_ENABLE_PROJECTS=clang" )

COMMON_CMAKE_FLAGS_REL=(
    "-DLLVM_OPTIMIZED_TABLEGEN=On"
    "-DCMAKE_BUILD_TYPE=Release"
    "-DENABLE_LINKER_BUILD_ID=On"
    "-DLLVM_TARGETS_TO_BUILD=X86"
    "-DLLVM_ENABLE_PROJECTS=clang" )

COMMON_BENCH_CMAKE_FLAGS=(
    "-DLLVM_OPTIMIZED_TABLEGEN=On"
    "-DCMAKE_BUILD_TYPE=Release"
    "-DLLVM_TARGETS_TO_BUILD=X86"
    "-DLLVM_ENABLE_PROJECTS=clang" )

CMAKE_COMPILER=(
    "-DCMAKE_C_COMPILER=${PATH_TO_LLVM_BUILDS}/symlinks/clang"
    "-DCMAKE_CXX_COMPILER=${PATH_TO_LLVM_BUILDS}/symlinks/clang++" )

CMAKE_BENCH_COMPILER=(
    "-DCMAKE_C_COMPILER=${PATH_TO_BENCHMARK_LLVM_BUILD}/symlinks/clang"
    "-DCMAKE_CXX_COMPILER=${PATH_TO_BENCHMARK_LLVM_BUILD}/symlinks/clang++" )

COMMON_LD_FLAGS=(
    "-DCMAKE_EXE_LINKER_FLAGS=-Wl,--build-id=sha1")
